name: op_assistant
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2023.7.22=hf0a4a13_0
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.42.0=hb31c410_0
  - libzlib=1.2.13=h53f4e23_5
  - ncurses=6.4=h7ea286d_0
  - openssl=3.1.2=h53f4e23_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.11.4=h47c9636_0_cpython
  - readline=8.2=h92ec313_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - wheel=0.41.1=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
      - altair==5.0.1
      - attrs==23.1.0
      - blinker==1.6.2
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.6
      - gitdb==4.0.10
      - gitpython==3.1.32
      - idna==3.4
      - importlib-metadata==6.8.0
      - jinja2==3.1.2
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - numpy==1.25.2
      - packaging==23.1
      - pandas==2.0.3
      - pillow==9.5.0
      - protobuf==4.24.0
      - pyarrow==12.0.1
      - pydeck==0.8.0
      - pygments==2.16.1
      - pympler==1.0.1
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pytz-deprecation-shim==0.1.0.post0
      - referencing==0.30.2
      - requests==2.31.0
      - rich==13.5.2
      - rpds-py==0.9.2
      - six==1.16.0
      - smmap==5.0.0
      - streamlit==1.25.0
      - tenacity==8.2.3
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.3.3
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - tzlocal==4.3.1
      - urllib3==2.0.4
      - validators==0.21.2
      - zipp==3.16.2
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/op_assistant
